version: "1"
services:

  harpoondemoback:
    image: harpoondemoback:latest
    ports:
      - "5000:5000"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017-27019:27017-27019"
    environment:
      MONGO_INITDB_DATABASE: "harpoondemo"
      MONGO_INITDB_ROOT_USERNAME: "admin"
      MONGO_INITDB_ROOT_PASSWORD: "admin"
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - type: volume
        source: mongodb
        target: /data
    command: mongod

volumes:
  mongodb:
